# Generated by Django 3.1.7 on 2021-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturantdata', '0002_order_orderitem_review_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
