[
    {
        "id": 1,
        "image": "/resturantdata/images/menu-item-01_x1vYA5W.jpg",
        "name": "Burger",
        "info": "Veg Cheesy Burger",
        "img": "https://user-images.githubusercontent.com/77019950/142701251-cf51b440-cd33-48e6-a386-580a36af0ebd.jpg",
        "category": "All",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 50
    },
    {
        "id": 2,
        "image": "/resturantdata/images/menu-item-02.jpg",
        "name": "Special Veg Biriyani",
        "info": "The extremely delicious desi ghee special Aromatic Biriyani.",
        "img": "https://user-images.githubusercontent.com/77019950/142701252-29bdfb7f-3de1-4ae9-b235-aff3fabd5560.jpg",
        "category": "Lunch & Dinner",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 100
    },
    {
        "id": 3,
        "image": "/resturantdata/images/menu-item-03.jpg",
        "name": "Grill Chicken",
        "info": "Whole Grilled Chicken with Wilted Arugula",
        "img": "https://user-images.githubusercontent.com/77019950/142701254-d4903280-f4b0-4fa6-98b9-2cd74564df1c.jpg",
        "category": "Lunch & Dinner",
        "rating": null,
        "numReviews": 0,
        "type": "Non-Veg",
        "price": 200
    },
    {
        "id": 4,
        "image": "/resturantdata/images/menu-item-04.jpg",
        "name": "Pizza",
        "info": "Classic Pizza",
        "img": "https://user-images.githubusercontent.com/77019950/142701258-9bebbed4-3acc-48ce-aa2e-73c2a5231899.jpg",
        "category": "All",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 70
    },
    {
        "id": 5,
        "image": "/resturantdata/images/menu-item-05.jpg",
        "name": "Barbecue",
        "info": "Meat US Dish from the collection of western barbecue including Chicken.",
        "img": "https://user-images.githubusercontent.com/77019950/142701241-a278bf7e-d6f1-4622-8bfb-479b39e63edb.jpg",
        "category": "Lunch & Dinner",
        "rating": null,
        "numReviews": 0,
        "type": "Non-Veg",
        "price": 400
    },
    {
        "id": 6,
        "image": "/resturantdata/images/menu-item-06.jpg",
        "name": "Dhokla",
        "info": "Snack is made with a fermented batter derived from rice and split chick peas.",
        "img": "https://user-images.githubusercontent.com/77019950/142701249-8e7a3e65-af3c-4ca7-98ba-d7917417c67b.jpg",
        "category": "Breakfast &Snack",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 50
    },
    {
        "id": 7,
        "image": "/resturantdata/images/menu-item-07.jpg",
        "name": "Shawarma",
        "info": "The specially prepared Chicken Shawarma",
        "img": "https://user-images.githubusercontent.com/77019950/144212690-0bb72ef3-94e6-4d1f-badd-09d8c7aeab69.jpg",
        "category": "Lunch & Dinner",
        "rating": null,
        "numReviews": 0,
        "type": "Non-Veg",
        "price": 70
    },
    {
        "id": 8,
        "image": "/resturantdata/images/menu-item08.jpg",
        "name": "Plain Cheese Pizza",
        "info": "The Authentic  Italian Cheesy Pizza.",
        "img": "https://user-images.githubusercontent.com/77019950/142701250-a7fcc935-3801-4f0b-aed3-8e884f171caf.jpg",
        "category": "Pizza",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 100
    },
    {
        "id": 9,
        "image": "/resturantdata/images/chocolate-mousse-cake.jpg",
        "name": "Dark Chocolate Pastry",
        "info": "This super moist dark chocolate mousse cake combines unsweetened natural cocoa powder and dark cocoa powder for an extra rich flavor.",
        "img": "https://user-images.githubusercontent.com/77019950/144214451-c7bc5b7f-3537-45e4-93ed-4410037218cd.jpg",
        "category": "Breakfast &Snack",
        "rating": null,
        "numReviews": 0,
        "type": "Veg",
        "price": 70
    }
]